config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'help'    => 'static_pages#help'
  resources :tasks
  resources :users
  #root "static_pages#home"
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy' 
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :status, inclusion: { in: ['To Do', 'In Progress', 'Done'] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to tasks_path
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end
    end
  
    def destroy
      log_out if logged_in?
      redirect_to root_url
    end
  end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    #@tasks = params[:status].present? ? Task.where(status: params[:status]).paginate(page: params[:page], per_page: 10) : Task.paginate(page: params[:page], per_page: 10)
    #@tasks = Task.paginate(page: params[:page], per_page: 10)
    # Filtering by status
    if params[:status].present?
      @tasks = Task.where(status: params[:status]).paginate(page: params[:page], per_page: 10)
    else
      @tasks = Task.paginate(page: params[:page], per_page: 10)
    end

    # Sorting by due date
    if params[:sort] == 'asc'
      @tasks = @tasks.order(due_date: :asc)
    elsif params[:sort] == 'desc'
      @tasks = @tasks.order(due_date: :desc)
    end
  end  

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    total_tasks_count = Task.count
    todo_tasks_count = Task.where(status: "To Do").count

    todo_tasks_percentage = (todo_tasks_count.to_f / total_tasks_count) * 100

    # Check if the percentage exceeds 50%
    if todo_tasks_percentage >= 50
      respond_to do |format|
        format.html { redirect_to tasks_path, notice: "Many tasks are in To Do status" }
        format.json { head :no_content }
      end
      return
    end
    @user = current_user
    @task = @user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :status, :due_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end  

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
    end
    
    # Returns true if the given user is the current user.
    def current_user?(user)
      user == current_user
    end
  
    # Returns the current logged-in user (if any).
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(:remember, cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end
  
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
      !current_user.nil?
    end
  
    # Logs out the current user.
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end
  

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end
  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Sai Krishna Pothireddy
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<% if !browser.device.mobile? %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "HabitNu", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
              <li>
              <% if !session[:culprit].blank? && !(session[:culprit] == current_user.id) %>
              <%= link_to "Original user", original_user_user_path(session[:culprit]) %>
              <% end %>
            </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<% else %>
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to "HabitNu", root_path, id: "logo" %>
      <nav>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                  <li>
              <% if !session[:culprit].blank? && !(session[:culprit] == current_user.id) %>
              <%= link_to "Original user", original_user_user_path(session[:culprit]) %>
              <% end %>
            </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HabitNu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>    
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title>About</title>
  </head>
  <body>
    <h1>About Me</h1>   
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Sai Krishna Pothireddy<br>
  Mobile : +91-8555853641<br>
  Mail : saikrishnapothireddy@gmail.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title>Help</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Please click <%= link_to "here", contact_path %> to get contact details for help.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
  </head>
  <body>
    <% if !logged_in? %>
    <div class="center jumbotron">
	  <h1>Welcome to HabitNu</h1>

	  <h2>Sign Up to enjoy the ultimate experience in the app</h2>

	  <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>

  <% else %>
  <%= react_component("Hello", { name: "react-rails" }) %>
    <%= link_to "Create Task", new_task_path, class: "btn btn-lg btn-primary" %>
  <% end %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true, html: { class: "task-form" }) do |form| %>
  <% if task.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, ['To Do', 'In Progress', 'Done'], { prompt: "Select status" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "datepicker" %>
  </div>

  <%= form.submit "Save", class: "btn btn-primary" %>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    flatpickr('.datepicker', {
    });
  });
</script>

app/views/tasks/_task.html.erb
<div id="<%= dom_id(task) %>" class="task-container">
  <div class="task-details">
    <p>
      <strong>Title:</strong>
      <%= task.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= task.description %>
    </p>

    <p>
      <strong>Due Date:</strong>
      <%= task.due_date %>
    </p>

    <p>
      <strong>Status:</strong>
      <div class="task-actions">
      <%= form_with(model: task, html: { class: "task-form" }) do |form| %>
        <%= form.select :status, ['To Do', 'In Progress', 'Done'], {}, { class: "status-select" } %>
      <% end %>
      </div>
    </p>
  </div>

  <div class="task-actions">
    <%= button_to "Delete", task, method: :delete, data: { confirm: "Are you sure you want to delete this task?" }, class: "btn btn-danger delete-btn" %>
    <%= link_to "Edit", edit_task_path(task), class: "btn btn-primary show-btn" %>
  </div>
</div>

<script>
  // Assuming you have jQuery included in your project
  $(document).ready(function() {
    $('.status-select').on('change', function() {
      $(this).closest('form').submit();
    });
  });
</script>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<% if !logged_in? %>
  <div class="center jumbotron">
    <h1>Welcome to HabitNu</h1>
    <h2>Sign Up to enjoy the ultimate experience in the app</h2>
    <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>
  </div>
<% else %>
  <div class="container">
    <p style="color: green"><%= notice %></p>

    <div class="row mb-3">
      <div class="col-md-6">
        <h1>Tasks</h1>
      </div>
      <div class="col-md-6 text-right">
        <%= link_to "Create Task", new_task_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
<p></p>
<div class="row mb-3">
<div class="col-md-3">
  <%= form_tag(tasks_path, method: :get) do %>
    <%= select_tag :status, options_for_select(['To Do', 'In Progress', 'Done'], params[:status]), prompt: "All", class: "form-control", onchange: "this.form.submit();" %>
    <%= hidden_field_tag :sort, params[:sort] %>
  <% end %>
</div>
<div class="col-md-3">
  <%= form_tag(tasks_path, method: :get, id: "sort-form") do %>
    <%= select_tag :sort, options_for_select({ "Ascending" => :asc, "Descending" => :desc }, params[:sort]), include_blank: "Sort by Due Date", class: "form-control", onchange: "this.form.submit();" %>
    <%= hidden_field_tag :status, params[:status] %>
  <% end %>
</div>
</div>

<p></p>
    <div class="row">
      <div class="col-md-12">
        <%= will_paginate %>
      </div>
    </div>

    <% @tasks.each do |task| %>
      <%= render task %>
    <% end %>

    <div class="row">
      <div class="col-md-12">
        <%= will_paginate %>
      </div>
    </div>
  </div>
<% end %>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const sortForm = document.getElementById("sort-form");
    const sortSelect = document.querySelector("#sort-form select");

    sortSelect.addEventListener("change", function() {
      sortForm.submit();
    });
  });
</script>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/users/_form.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :Profile_pic %>
      <%= f.file_field :avatar %>
      <h1></h1>
      <%= f.submit "Create my account", class: "btn btn-primary" %><h1></h1>
      <h5><strong>Already a user?</strong> <%= link_to "Log in", login_path %> </h5>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= link_to gravatar_for user %>
        <%= link_to "#{user.name}", user_path(user) %>
      </h1>
    </section>
  </aside>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Users</h1>
<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>